function plotHandle = animateMarkers(ii, plotHandle, Markers, varargin)
    if isempty(plotHandle)
        plotHandle = plot3( ...
            squeeze(Markers(ii, 1, :)), ...
            squeeze(Markers(ii, 2, :)), ...
            squeeze(Markers(ii, 3, :)), ...
            varargin{:} ...
        );
    else
        plotHandle.XData = Markers(ii, 1, :);
        plotHandle.YData = Markers(ii, 2, :);
        plotHandle.ZData = Markers(ii, 3, :);
    end
end