function plotHandle = animateForces(ii, plotHandle, applicationPoint, forceMat, varargin)
    if isempty(plotHandle)
        plotHandle = quiver3( ...
            squeeze(applicationPoint(ii, 1, :)), ...
            squeeze(applicationPoint(ii, 2, :)), ...
            squeeze(applicationPoint(ii, 3, :)), ...
            squeeze(forceMat(ii, 1, :)), ...
            squeeze(forceMat(ii, 2, :)), ...
            squeeze(forceMat(ii, 3, :)), ...
            varargin{:} ...
        );
    else
        plotHandle.XData = applicationPoint(ii, 1, :);
        plotHandle.YData = applicationPoint(ii, 2, :);
        plotHandle.ZData = applicationPoint(ii, 3, :);
        plotHandle.UData = forceMat(ii, 1, :);
        plotHandle.VData = forceMat(ii, 2, :);
        plotHandle.WData = forceMat(ii, 3, :);
    end
end