function plotHandle = animatePoint(ii, plotHandle, pointCoords, varargin)
    if isempty(plotHandle)
        plotHandle = scatter3( ...
            squeeze(pointCoords(ii, 1, :)), ...
            squeeze(pointCoords(ii, 2, :)), ...
            squeeze(pointCoords(ii, 3, :)), ...
            varargin{:} ...
        );
    else
        plotHandle.XData = pointCoords(ii, 1, :);
        plotHandle.YData = pointCoords(ii, 2, :);
        plotHandle.ZData = pointCoords(ii, 3, :);
    end
end