function plotHandle = animatePlanarMarkers(ii, plotHandle, Markers, varargin)
    if isempty(plotHandle)
        plotHandle = plot( ...
            squeeze(Markers(ii, 1, :)), ...
            squeeze(Markers(ii, 2, :)), ...
            varargin{:} ...
        );
    else
        plotHandle.XData = Markers(ii, 1, :);
        plotHandle.YData = Markers(ii, 2, :);
    end
end