function centersOfPressure = forces2Cop(Forces, tol)
    if nargin < 2
        tol = 1e-3;
    end
    centersOfPressure = cat(2, ...
        -Forces(:, 5, :) ./ Forces(:, 3, :), ...
         Forces(:, 4, :) ./ Forces(:, 3, :), ...
         zeros(size(Forces(:, 3, :))) ...
     );
    % Undefined CoP if vertical GRF is too small
    centersOfPressure(repmat(Forces(:, 3, :), [1, 3, 1]) < tol) = nan;
end