function plotHandles = planarMarkersPlotTrace(Markers, MarkerNames, varargin)

colors = linspecer(size(Markers, 3));
plotHandles = [];

for n = 1 : size(Markers, 3)
    plotHandles(end+1) = ...
    plot( ...
        squeeze(Markers(:, 1, n)), ...
        squeeze(Markers(:, 2, n)), ...
        'Color', colors(n, :), ...
        'DisplayName', MarkerNames(n), ...
        varargin{:} ...
    );
end

end